language: csharp
solution: Inheritence/Inheritence.sln

dotnet: latest
script:
    - dotnet restore
    - dotnet test Inheritence/Inheritence.sln
    - dotnet run Inheritance/Inheritance.sln --project Inheritance/src/Inheritance/           
