language: csharp
solution: Inheritence/Inheritence.sln

mono: none
dotnet: 3.0
script:
    - dotnet restore Inheritence
    - dotnet test Inheritence
    - dotnet run Inheritance/Inheritance.sln --project Inheritance/src/Inheritance/           
